// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-alumni.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_alumni_default = defineTool({
  name: "search_alumni",
  title: "Search alumni directory",
  description: "Search the alumni directory by name, company, specialization, graduation year, location, or candidate type. Returns non-sensitive public profile fields.",
  inputSchema: {
    query: z.string().optional().describe("Free-text match against name, company, job title, or bio."),
    graduation_year: z.number().int().optional(),
    specialization: z.string().optional(),
    location: z.string().optional(),
    candidate_type: z.enum(["Domestic", "International"]).optional(),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, graduation_year, specialization, location, candidate_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("alumni_profiles_public").select("*").limit(limit ?? 20);
    if (graduation_year) q = q.eq("graduation_year", graduation_year);
    if (specialization) q = q.eq("specialization", specialization);
    if (location) q = q.ilike("location", `%${location}%`);
    if (candidate_type) q = q.eq("candidate_type", candidate_type);
    if (query) {
      q = q.or(
        `full_name.ilike.%${query}%,company.ilike.%${query}%,job_title.ilike.%${query}%,bio.ilike.%${query}%`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my alumni profile",
  description: "Return the signed-in alumni's own profile (including private fields).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("alumni_profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool3({
  name: "list_upcoming_events",
  title: "List upcoming events",
  description: "List approved upcoming alumni events.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("events").select("id, title, description, event_date, location, event_type, host_name, created_at").eq("status", "approved").gte("event_date", (/* @__PURE__ */ new Date()).toISOString()).order("event_date", { ascending: true }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-referrals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_referrals_default = defineTool4({
  name: "list_referrals",
  title: "List job referrals",
  description: "List approved, active job referral offers and requests posted by alumni.",
  inputSchema: {
    referral_type: z3.enum(["offering", "requesting"]).optional(),
    company: z3.string().optional(),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ referral_type, company, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("referrals").select("*").eq("status", "approved").eq("is_active", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (referral_type) q = q.eq("referral_type", referral_type);
    if (company) q = q.ilike("company", `%${company}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { referrals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-groups.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_groups_default = defineTool5({
  name: "list_groups",
  title: "List alumni groups",
  description: "List approved alumni groups and communities.",
  inputSchema: {
    query: z4.string().optional().describe("Free-text match against name or description."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    let q = sb.from("groups").select("id, name, description, category, cover_image_url, created_at").eq("status", "approved").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-community-post.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_community_post_default = defineTool6({
  name: "create_community_post",
  title: "Create a community post",
  description: "Create a new post in the community feed as the signed-in alumni. Optionally scope to a group the user belongs to.",
  inputSchema: {
    content: z5.string().trim().min(1).max(4e3),
    group_id: z5.string().uuid().optional().describe("Group to scope the post to (must be a member).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ content, group_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("posts").insert({ user_id: ctx.getUserId(), content, group_id: group_id ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Post created: ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "unmdpiavvvjaipnvhnum";
var mcp_default = defineMcp({
  name: "studentlink-ai-mcp",
  title: "StudentLink AI MCP",
  version: "0.1.0",
  instructions: "Tools for the StudentLink AI network. Search alumni, view your own profile, list upcoming events, browse job referrals, discover groups, and post to the community feed. All calls act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_alumni_default,
    get_my_profile_default,
    list_events_default,
    list_referrals_default,
    list_groups_default,
    create_community_post_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
